name: schedule run

on:
  schedule:
    # Run every Monday at 1:00 AM UTC = 6:30 AM IST
    - cron: '0 1 * * 1'
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get current time
        uses: josStorer/get-current-time@v2.0.1
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.2'
          check-latest: true

      - name: Run main.go
        env:  # Set environment variables from secrets
          H1_USERNAME: ${{ secrets.H1_USERNAME }}
          H1_TOKEN: ${{ secrets.H1_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          go run ./cmd/bbnotifier/main.go

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated on ${{ steps.current-time.outputs.readableTime }}" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
